// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIlUKEVBvbGlzaFRleHRSZXF1ZXN0EhEKBHRleHQYASABKAlCA+BBAhIYCgtpbnN0cnVjdGlvbhgCIAEoCUID4EEBEhMKBnByZXNldBgDIAEoCUID4EEBIiIKElBvbGlzaFRleHRSZXNwb25zZRIMCgR0ZXh0GAEgASgJIkMKFkdlbmVyYXRlRm9ybXVsYVJlcXVlc3QSEwoGcHJvbXB0GAEgASgJQgPgQQISFAoHY29udGV4dBgCIAEoCUID4EEBIioKF0dlbmVyYXRlRm9ybXVsYVJlc3BvbnNlEg8KB2Zvcm11bGEYASABKAkiQQoVRm9ybWF0TWFya2Rvd25SZXF1ZXN0EhEKBHRleHQYASABKAlCA+BBAhIVCghmaWxlbmFtZRgCIAEoCUID4EEBIioKFkZvcm1hdE1hcmtkb3duUmVzcG9uc2USEAoIbWFya2Rvd24YASABKAkiSQoRVHJhbnNjcmliZVJlcXVlc3QSNAoFYXVkaW8YASABKAsyIC5tZW1vcy5hcGkudjEuVHJhbnNjcmlwdGlvbkF1ZGlvQgPgQQIidwoSVHJhbnNjcmlwdGlvbkF1ZGlvEhYKB2NvbnRlbnQYASABKAxCA+BBBEgAEg0KA3VyaRgCIAEoCUgAEhUKCGZpbGVuYW1lGAMgASgJQgPgQQESGQoMY29udGVudF90eXBlGAQgASgJQgPgQQFCCAoGc291cmNlIiIKElRyYW5zY3JpYmVSZXNwb25zZRIMCgR0ZXh0GAEgASgJMqkECglBSVNlcnZpY2USeQoKVHJhbnNjcmliZRIfLm1lbW9zLmFwaS52MS5UcmFuc2NyaWJlUmVxdWVzdBogLm1lbW9zLmFwaS52MS5UcmFuc2NyaWJlUmVzcG9uc2UiKNpBBWF1ZGlvgtPkkwIaOgEqIhUvYXBpL3YxL2FpOnRyYW5zY3JpYmUSiAEKDkZvcm1hdE1hcmtkb3duEiMubWVtb3MuYXBpLnYxLkZvcm1hdE1hcmtkb3duUmVxdWVzdBokLm1lbW9zLmFwaS52MS5Gb3JtYXRNYXJrZG93blJlc3BvbnNlIivaQQR0ZXh0gtPkkwIeOgEqIhkvYXBpL3YxL2FpOmZvcm1hdE1hcmtkb3duEoQBCgpQb2xpc2hUZXh0Eh8ubWVtb3MuYXBpLnYxLlBvbGlzaFRleHRSZXF1ZXN0GiAubWVtb3MuYXBpLnYxLlBvbGlzaFRleHRSZXNwb25zZSIz2kEQdGV4dCxpbnN0cnVjdGlvboLT5JMCGjoBKiIVL2FwaS92MS9haTpwb2xpc2hUZXh0Eo4BCg9HZW5lcmF0ZUZvcm11bGESJC5tZW1vcy5hcGkudjEuR2VuZXJhdGVGb3JtdWxhUmVxdWVzdBolLm1lbW9zLmFwaS52MS5HZW5lcmF0ZUZvcm11bGFSZXNwb25zZSIu2kEGcHJvbXB0gtPkkwIfOgEqIhovYXBpL3YxL2FpOmdlbmVyYXRlRm9ybXVsYUKmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.PolishTextRequest
 */
export type PolishTextRequest = Message<"memos.api.v1.PolishTextRequest"> & {
  /**
   * Required. The selected text to rewrite.
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * Optional. A custom instruction describing how to rewrite the text
   * (e.g. "make it more formal", "cut the length in half"). When empty,
   * the preset field is used.
   *
   * @generated from field: string instruction = 2;
   */
  instruction: string;

  /**
   * Optional. A named preset action, used when instruction is empty.
   * One of: "polish", "concise", "expand", "grammar", "tone".
   *
   * @generated from field: string preset = 3;
   */
  preset: string;
};

/**
 * Describes the message memos.api.v1.PolishTextRequest.
 * Use `create(PolishTextRequestSchema)` to create a new message.
 */
export const PolishTextRequestSchema: GenMessage<PolishTextRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.PolishTextResponse
 */
export type PolishTextResponse = Message<"memos.api.v1.PolishTextResponse"> & {
  /**
   * The rewritten text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.PolishTextResponse.
 * Use `create(PolishTextResponseSchema)` to create a new message.
 */
export const PolishTextResponseSchema: GenMessage<PolishTextResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.GenerateFormulaRequest
 */
export type GenerateFormulaRequest = Message<"memos.api.v1.GenerateFormulaRequest"> & {
  /**
   * Required. A natural-language description of the formula to generate
   * (e.g. "sum the price column", "average of B2 to B10").
   *
   * @generated from field: string prompt = 1;
   */
  prompt: string;

  /**
   * Optional. Spreadsheet context to ground the formula, such as the active
   * cell reference and the sheet's header row / sample rows.
   *
   * @generated from field: string context = 2;
   */
  context: string;
};

/**
 * Describes the message memos.api.v1.GenerateFormulaRequest.
 * Use `create(GenerateFormulaRequestSchema)` to create a new message.
 */
export const GenerateFormulaRequestSchema: GenMessage<GenerateFormulaRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.GenerateFormulaResponse
 */
export type GenerateFormulaResponse = Message<"memos.api.v1.GenerateFormulaResponse"> & {
  /**
   * The generated formula, beginning with "=".
   *
   * @generated from field: string formula = 1;
   */
  formula: string;
};

/**
 * Describes the message memos.api.v1.GenerateFormulaResponse.
 * Use `create(GenerateFormulaResponseSchema)` to create a new message.
 */
export const GenerateFormulaResponseSchema: GenMessage<GenerateFormulaResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.FormatMarkdownRequest
 */
export type FormatMarkdownRequest = Message<"memos.api.v1.FormatMarkdownRequest"> & {
  /**
   * Required. The plain text to format.
   *
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * Optional. The source filename, used as context for the model.
   *
   * @generated from field: string filename = 2;
   */
  filename: string;
};

/**
 * Describes the message memos.api.v1.FormatMarkdownRequest.
 * Use `create(FormatMarkdownRequestSchema)` to create a new message.
 */
export const FormatMarkdownRequestSchema: GenMessage<FormatMarkdownRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from message memos.api.v1.FormatMarkdownResponse
 */
export type FormatMarkdownResponse = Message<"memos.api.v1.FormatMarkdownResponse"> & {
  /**
   * The markdown-formatted text.
   *
   * @generated from field: string markdown = 1;
   */
  markdown: string;
};

/**
 * Describes the message memos.api.v1.FormatMarkdownResponse.
 * Use `create(FormatMarkdownResponseSchema)` to create a new message.
 */
export const FormatMarkdownResponseSchema: GenMessage<FormatMarkdownResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 5);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 6);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 7);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 8);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * FormatMarkdown restructures plain text into markdown using an instance AI provider,
   * preserving the original text content verbatim.
   *
   * @generated from rpc memos.api.v1.AIService.FormatMarkdown
   */
  formatMarkdown: {
    methodKind: "unary";
    input: typeof FormatMarkdownRequestSchema;
    output: typeof FormatMarkdownResponseSchema;
  },
  /**
   * PolishText rewrites a selected span of text using an instance AI provider,
   * following a preset or custom instruction, and returns the rewritten text.
   *
   * @generated from rpc memos.api.v1.AIService.PolishText
   */
  polishText: {
    methodKind: "unary";
    input: typeof PolishTextRequestSchema;
    output: typeof PolishTextResponseSchema;
  },
  /**
   * GenerateFormula produces a spreadsheet formula from a natural-language prompt
   * using an instance AI provider, returning only the formula string.
   *
   * @generated from rpc memos.api.v1.AIService.GenerateFormula
   */
  generateFormula: {
    methodKind: "unary";
    input: typeof GenerateFormulaRequestSchema;
    output: typeof GenerateFormulaResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

