// @generated by protoc-gen-es v2.16.0 with parameter "target=ts"
// @generated from file api/v1/rag_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/rag_service.proto.
 */
export const file_api_v1_rag_service: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvdjEvcmFnX3NlcnZpY2UucHJvdG8SDG1lbW9zLmFwaS52MSKpAQoNU2VhcmNoUmVxdWVzdBISCgVxdWVyeRgBIAEoCUID4EECEhAKBmdsb2JhbBgCIAEoCEgAEhMKCXdvcmtzcGFjZRgDIAEoCUgAEisKBG1vZGUYBCABKA4yGC5tZW1vcy5hcGkudjEuU2VhcmNoTW9kZUID4EEBEhIKBWxpbWl0GAUgASgFQgPgQQESEwoGZmlsdGVyGAYgASgJQgPgQQFCBwoFc2NvcGUikgEKCVNlYXJjaEhpdBIMCgRtZW1vGAEgASgJEg0KBXRpdGxlGAIgASgJEhEKCXdvcmtzcGFjZRgDIAEoCRITCgtmb2xkZXJfcGF0aBgEIAEoCRINCgVzY29yZRgFIAEoARIPCgdzbmlwcGV0GAYgASgJEhIKCmhpZ2hsaWdodHMYByADKAkSDAoEaWNvbhgIIAEoCSJpCg5TZWFyY2hSZXNwb25zZRIlCgRoaXRzGAEgAygLMhcubWVtb3MuYXBpLnYxLlNlYXJjaEhpdBIwCg5lZmZlY3RpdmVfbW9kZRgCIAEoDjIYLm1lbW9zLmFwaS52MS5TZWFyY2hNb2RlIhUKE1JlYnVpbGRJbmRleFJlcXVlc3QiKAoUUmVidWlsZEluZGV4UmVzcG9uc2USEAoIZW5xdWV1ZWQYASABKAUiFwoVR2V0SW5kZXhTdGF0dXNSZXF1ZXN0InkKFkdldEluZGV4U3RhdHVzUmVzcG9uc2USDwoHcGVuZGluZxgBIAEoBRISCgpwcm9jZXNzaW5nGAIgASgFEg4KBmZhaWxlZBgDIAEoBRIMCgRkb25lGAQgASgFEhwKFGVtYmVkZGluZ19jb25maWd1cmVkGAUgASgIKokBCgpTZWFyY2hNb2RlEhsKF1NFQVJDSF9NT0RFX1VOU1BFQ0lGSUVEEAASFQoRU0VBUkNIX01PREVfTUlYRUQQARIXChNTRUFSQ0hfTU9ERV9LRVlXT1JEEAISGAoUU0VBUkNIX01PREVfU0VNQU5USUMQAxIUChBTRUFSQ0hfTU9ERV9MSUtFEAQy6gIKClJhZ1NlcnZpY2USYgoGU2VhcmNoEhsubWVtb3MuYXBpLnYxLlNlYXJjaFJlcXVlc3QaHC5tZW1vcy5hcGkudjEuU2VhcmNoUmVzcG9uc2UiHYLT5JMCFzoBKiISL2FwaS92MS9yYWc6c2VhcmNoEnoKDFJlYnVpbGRJbmRleBIhLm1lbW9zLmFwaS52MS5SZWJ1aWxkSW5kZXhSZXF1ZXN0GiIubWVtb3MuYXBpLnYxLlJlYnVpbGRJbmRleFJlc3BvbnNlIiOC0+STAh06ASoiGC9hcGkvdjEvcmFnOnJlYnVpbGRJbmRleBJ8Cg5HZXRJbmRleFN0YXR1cxIjLm1lbW9zLmFwaS52MS5HZXRJbmRleFN0YXR1c1JlcXVlc3QaJC5tZW1vcy5hcGkudjEuR2V0SW5kZXhTdGF0dXNSZXNwb25zZSIfgtPkkwIZEhcvYXBpL3YxL3JhZy9pbmRleFN0YXR1c0KnAQoQY29tLm1lbW9zLmFwaS52MUIPUmFnU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.SearchRequest
 */
export type SearchRequest = Message<"memos.api.v1.SearchRequest"> & {
  /**
   * Required. The search query.
   *
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from oneof memos.api.v1.SearchRequest.scope
   */
  scope: {
    /**
     * Search across all workspaces the user can access.
     *
     * @generated from field: bool global = 2;
     */
    value: boolean;
    case: "global";
  } | {
    /**
     * Restrict search to a single workspace, identified by its resource name.
     * Format: workspaces/{workspace}
     *
     * @generated from field: string workspace = 3;
     */
    value: string;
    case: "workspace";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. Retrieval mode. Unspecified falls back to the user's configured mode.
   *
   * @generated from field: memos.api.v1.SearchMode mode = 4;
   */
  mode: SearchMode;

  /**
   * Optional. Max documents to return. Zero falls back to the user's configured limit.
   *
   * @generated from field: int32 limit = 5;
   */
  limit: number;

  /**
   * Optional. A CEL filter (same grammar as ListMemos.filter) that constrains the
   * candidate document set BEFORE ranking. Structured conditions (workspace, tag,
   * visibility, time, doc_type, …) define the corpus; the query then ranks within it.
   * The keyword itself must NOT be encoded here as content.contains — pass it as `query`
   * so semantic recall isn't lost. Permission scoping is always applied on top.
   *
   * @generated from field: string filter = 6;
   */
  filter: string;
};

/**
 * Describes the message memos.api.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export const SearchRequestSchema: GenMessage<SearchRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 0);

/**
 * @generated from message memos.api.v1.SearchHit
 */
export type SearchHit = Message<"memos.api.v1.SearchHit"> & {
  /**
   * The memo resource name. Format: memos/{memo}
   *
   * @generated from field: string memo = 1;
   */
  memo: string;

  /**
   * The memo's user-facing title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * The workspace resource name the memo belongs to. Format: workspaces/{workspace}
   *
   * @generated from field: string workspace = 3;
   */
  workspace: string;

  /**
   * The memo's folder path within its workspace.
   *
   * @generated from field: string folder_path = 4;
   */
  folderPath: string;

  /**
   * Fused relevance score (higher is more relevant).
   *
   * @generated from field: double score = 5;
   */
  score: number;

  /**
   * Best-matching snippet of the memo's content.
   *
   * @generated from field: string snippet = 6;
   */
  snippet: string;

  /**
   * Substrings within the snippet that matched the query, for client-side highlighting.
   *
   * @generated from field: repeated string highlights = 7;
   */
  highlights: string[];

  /**
   * The memo's emoji icon, empty for the doc-type default.
   *
   * @generated from field: string icon = 8;
   */
  icon: string;
};

/**
 * Describes the message memos.api.v1.SearchHit.
 * Use `create(SearchHitSchema)` to create a new message.
 */
export const SearchHitSchema: GenMessage<SearchHit> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 1);

/**
 * @generated from message memos.api.v1.SearchResponse
 */
export type SearchResponse = Message<"memos.api.v1.SearchResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.SearchHit hits = 1;
   */
  hits: SearchHit[];

  /**
   * The mode actually applied (may be downgraded to KEYWORD when no embedding model is configured).
   *
   * @generated from field: memos.api.v1.SearchMode effective_mode = 2;
   */
  effectiveMode: SearchMode;
};

/**
 * Describes the message memos.api.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export const SearchResponseSchema: GenMessage<SearchResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 2);

/**
 * @generated from message memos.api.v1.RebuildIndexRequest
 */
export type RebuildIndexRequest = Message<"memos.api.v1.RebuildIndexRequest"> & {
};

/**
 * Describes the message memos.api.v1.RebuildIndexRequest.
 * Use `create(RebuildIndexRequestSchema)` to create a new message.
 */
export const RebuildIndexRequestSchema: GenMessage<RebuildIndexRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 3);

/**
 * @generated from message memos.api.v1.RebuildIndexResponse
 */
export type RebuildIndexResponse = Message<"memos.api.v1.RebuildIndexResponse"> & {
  /**
   * Number of memos enqueued for reindexing.
   *
   * @generated from field: int32 enqueued = 1;
   */
  enqueued: number;
};

/**
 * Describes the message memos.api.v1.RebuildIndexResponse.
 * Use `create(RebuildIndexResponseSchema)` to create a new message.
 */
export const RebuildIndexResponseSchema: GenMessage<RebuildIndexResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 4);

/**
 * @generated from message memos.api.v1.GetIndexStatusRequest
 */
export type GetIndexStatusRequest = Message<"memos.api.v1.GetIndexStatusRequest"> & {
};

/**
 * Describes the message memos.api.v1.GetIndexStatusRequest.
 * Use `create(GetIndexStatusRequestSchema)` to create a new message.
 */
export const GetIndexStatusRequestSchema: GenMessage<GetIndexStatusRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 5);

/**
 * @generated from message memos.api.v1.GetIndexStatusResponse
 */
export type GetIndexStatusResponse = Message<"memos.api.v1.GetIndexStatusResponse"> & {
  /**
   * pending is the number of memos waiting to be indexed.
   *
   * @generated from field: int32 pending = 1;
   */
  pending: number;

  /**
   * processing is the number of memos currently being indexed.
   *
   * @generated from field: int32 processing = 2;
   */
  processing: number;

  /**
   * failed is the number of memos whose indexing failed.
   *
   * @generated from field: int32 failed = 3;
   */
  failed: number;

  /**
   * done is the number of memos successfully indexed.
   *
   * @generated from field: int32 done = 4;
   */
  done: number;

  /**
   * embedding_configured reports whether a semantic-search embedding model is set up.
   *
   * @generated from field: bool embedding_configured = 5;
   */
  embeddingConfigured: boolean;
};

/**
 * Describes the message memos.api.v1.GetIndexStatusResponse.
 * Use `create(GetIndexStatusResponseSchema)` to create a new message.
 */
export const GetIndexStatusResponseSchema: GenMessage<GetIndexStatusResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_rag_service, 6);

/**
 * SearchMode mirrors store.RagSearchMode for the API surface.
 *
 * @generated from enum memos.api.v1.SearchMode
 */
export enum SearchMode {
  /**
   * @generated from enum value: SEARCH_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEARCH_MODE_MIXED = 1;
   */
  MIXED = 1,

  /**
   * @generated from enum value: SEARCH_MODE_KEYWORD = 2;
   */
  KEYWORD = 2,

  /**
   * @generated from enum value: SEARCH_MODE_SEMANTIC = 3;
   */
  SEMANTIC = 3,

  /**
   * Plain substring (SQL LIKE) retrieval over raw memo title/content, bypassing
   * the search index entirely.
   *
   * @generated from enum value: SEARCH_MODE_LIKE = 4;
   */
  LIKE = 4,
}

/**
 * Describes the enum memos.api.v1.SearchMode.
 */
export const SearchModeSchema: GenEnum<SearchMode> = /*@__PURE__*/
  enumDesc(file_api_v1_rag_service, 0);

/**
 * @generated from service memos.api.v1.RagService
 */
export const RagService: GenService<{
  /**
   * Search runs a hybrid (full-text + semantic) search over the memos the current
   * user can access. Global search and in-library search share this RPC, differing
   * only by scope.
   *
   * @generated from rpc memos.api.v1.RagService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
  /**
   * RebuildIndex clears and re-enqueues the entire search index. Instance owners only.
   *
   * @generated from rpc memos.api.v1.RagService.RebuildIndex
   */
  rebuildIndex: {
    methodKind: "unary";
    input: typeof RebuildIndexRequestSchema;
    output: typeof RebuildIndexResponseSchema;
  },
  /**
   * GetIndexStatus returns the current index queue progress.
   *
   * @generated from rpc memos.api.v1.RagService.GetIndexStatus
   */
  getIndexStatus: {
    methodKind: "unary";
    input: typeof GetIndexStatusRequestSchema;
    output: typeof GetIndexStatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_rag_service, 0);

