allowBuilds:
  core-js: false
  es5-ext: false
  esbuild: true
  x-data-spreadsheet: false

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - core-js
  - es5-ext
  - x-data-spreadsheet
